import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Nav from '../../components/Nav/Nav';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Book List',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	// Receive messages provided in `i18n.ts`
	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					{/* Navigation */}
					<Nav />
					<main className='flex min-h-screen flex-col items-center pt-10 pb-24 '>
						{children}
					</main>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
